---
apiVersion: v1
kind: Service
metadata:
  name: prodxcloud-store
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: prodxcloud-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80