name: Scan Docker Image CI Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
jobs:
  trivyScanDockerImage:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/joelwembo/prodxcloud-store:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/joelwembo/prodxcloud-store:${{ github.sha }}'
          format: 'table'
        #   exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'